services:
  postgres-f1:
    image: postgres:16
    container_name: postgres-f1
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_f1_data:/var/lib/postgresql/data

volumes:
  postgres_f1_data: